# Generated by Django 3.2.9 on 2023-03-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('link', models.TextField()),
                ('category', models.TextField()),
                ('img', models.TextField()),
            ],
        ),
    ]
